{{- if .Values.spark.install }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-dependencies-role
  labels:
    name: spark-dependencies-role
    app.kubernetes.io/name: spark-dependencies-role
    app.kubernetes.io/instance: {{ cat "jaeger-spark-dependencies-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger-spark-dependencies
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments/status
      - daemonsets/status
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
      - patch
{{- end }}
